apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: spring-crud-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-crud-demo
  template:
    metadata:
      labels:
        app: spring-crud-demo
    spec:
      containers:
      - name: spring-crud-demo
        image: gcr.io/high-wave-368116/spring-demo:1.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: DB_HOST
            value: mysql
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: spring-crud-demo
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
